# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4750b69eebd67e502c1842af2fdca5704f00318aa39f71372d9fdcb48a396c75b5b8f297b003d0d9d1df5b8965fca84bb1648cc50a2320a514a496c4f986de3c

test:
  secret_key_base: e35c8df8b883bcdde7a6429a3902f7644b1b3966ee603a419e45031778f6dd8e5fa0bfbac2ba07fce18babd0ebe620dfb419d51ca9a44001190266f79a98bb74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
